### ISSUE TITLE
Exception in thread "main" 

### ISSUE THREAD

**Issue by lollita** [AlessioScarfone/Java-Digital-Signature#7]
Windows 10
openjdk version "21.0.1" 2023-10-17 LTS

When try:
"%ProgramFiles%\Java\openJRE\bin\java.exe" -jar signer.jar --driver %SystemRoot%\system32\mydriver.dll -i
I get:

Use driver located in: C:\WINDOWS\system32\mydriver.dll
Password:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.IllegalAccessError: class eu.europa.esig.dss.token.Pkcs11SignatureToken (in unnamed module @0x35f983a6) cannot access class sun.security.pkcs11.SunPKCS11 (in module jdk.crypto.cryptoki) because module jdk.crypto.cryptoki does not export sun.security.pkcs11 to unnamed module @0x35f983a6
        at eu.europa.esig.dss.token.Pkcs11SignatureToken.installProvider(Pkcs11SignatureToken.java:154)
        at eu.europa.esig.dss.token.Pkcs11SignatureToken.getProvider(Pkcs11SignatureToken.java:130)
        at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:174)
        at eu.europa.esig.dss.token.AbstractKeyStoreTokenConnection.getKeys(AbstractKeyStoreTokenConnection.java:24)
        at com.unical.digitalsignature.Main.showInfo(Main.java:132)
        at com.unical.digitalsignature.Main.main(Main.java:92)
        ... 3 more

how to solve?
grazie.

**Comment by AlessioScarfone** [comment]
Hi @lollita,
try with an older version of jdk.

The code is tested only on Windows 10 and 8.1 with Oracle JDK8

**Comment by lollita** [comment]
With 8 work fine.
ty.
